---
- name: install server role
  hosts: ipaserver
  vars_files:
    - ./vars/install_vars.yml
  pre_tasks:
    - name: set the firewall rules first
      ansible.builtin.import_tasks: firewall_config_verify.yml 
  tasks:
    - name: import & install ipa server.
      role:
      name: ipaserver
