---
- name: install client
  hosts: lprom.l-org.lan
  vars_files:
    - ./vars/install_vars.yml
    - ./vars/client_vars.yml
  pre_tasks:
    - name: create a conditional workflow
      block:
      - name: install with yum module if running RedHat
        ansible.builtin.yum:
          name: "{{ item.name }}"
          state: "{{ item.state }}"
        changed_when: ansible_facts["distribution"] == 'RedHat'
        loop: "{{ ipa_yum.packages }}"

      rescue:
      - name: install with apt module if running Ubuntu
        ansible.builtin.apt:
          name: pip
          state: present
        changed_when: ansible_facts["distribution"] == 'Ubuntu'

      - name: make sure the ipapython library is installed.
        ansible.builtin.apt:
          name: python3-ipaclient
          state: present
      
      always:
      - name: make sure the ipapython library is installed.
        ansible.builtin.pip:
          name: ipapython
          state: present
          extra_args: --user

  tasks:
    - name: install ipa clients
      import_role:
        name: ipaclient
