---
- name: install client
  hosts: ipaclients
  vars_files:
    - ./vars/install_vars.yml
    - ./vars/client_vars.yml
  tasks:
    - name: install ipa clients
      import_role:
        name: ipaclient
