---
- name: Install IPA servers
  hosts: ipaserver
  become: true
  vars_files:
    - ./vars/install_vars.yml

  roles:
  - role: ipaserver
    state: present

- name: Install IPA replicas
  hosts: ipareplicas
  become: true
  vars_files:
    - ./vars/install_vars.yml

  roles:
  - role: ipareplica
    state: present

- name: Install IPA clients
  hosts: ipaclients
  become: true
  vars_files:
    - ./vars/install_vars.yml

  roles:
  - role: ipaclient
    state: present
