---
- name: run the entire ipa install. 
  hosts: ipaserver
  vars_files:
    - ./vars/install_vars.yml

  pre_tasks:
    - name: set the firewall rules first
      ansible.builtin.import_tasks: firewall_config_verify.yml 

  tasks:
    - name: import the install-server install tasks
      ansible.builtin.import_role: 
        name: ./roles/ipaserver

    - name: import the install-client install tasks
      ansible.builtin.import_role: 
        name: ./roles/ipaclient
